### ISSUE TITLE
Some Recipes problem

### ISSUE THREAD

**Issue by openipka** [GregTechCEu/gregicality#575] opened 2021-07-28 07:51 UTC
----Main Mod List----
Gregicality-1.12.2-0.22.7
gregtech-1.12.2-1.17.0.764
gregtech-1.12.2-1.17.0.764-energy-api
gregtech-1.12.2-1.17.0.764-sources

----Problems----
1.Missing recipe for Laser Engraving Casing.
2.two recipes for all gadgets like rotors, pumps, conveyors, etc.
3.Conflicting(?) recipes between pumps and conveyors.

----Details----
1.As said above, unable to craft laser Engraving casing and no recipe shows  in JEI.
2.I guess those recipes are one from GTCE and one from Gi and somehow Gi recipes didn't overlap the GTCE recipes. And of course GTCE recipes conflict with Gi recipes. For example, pumps and Conveyors.
![2021-07-28_152453](https://user-images.githubusercontent.com/78248875/127283657-4492cc4b-4bc8-41ac-83d2-81bff73f9a71.png)
![2021-07-28_152514](https://user-images.githubusercontent.com/78248875/127283653-c01aecda-1066-4660-ac2e-6d7a3ff541f0.png)
![2021-07-28_152527](https://user-images.githubusercontent.com/78248875/127283654-5b6c4821-a281-468e-b26b-237678e57411.png)
![2021-07-28_152545](https://user-images.githubusercontent.com/78248875/127283655-66965fa1-d98c-4696-b517-4f4b8c9ed2d4.png)
The first belongs to GTCE and the second belongs to Gi. 
3.As showed above, I don't know if it's a feature or something else. Difference between two of them is  the amount of rubber used. So when the rubber is sufficient the conveyor recipe will always cover pump recipe which makes pumps unable to be assembled. It may be a trick to force players use continuous supply of rubber instead putting it altogether in the assembler...

**Comment by warjort** [comment] 2021-07-28 16:20
You don't want the gregtech-energy-api and gregtech-sources jar loaded in production. 
These are used for development.
With these loaded and the main gregtech jar loaded you will have duplicate classes and assets.

I don't know if that is the cause of your problem, just a suggestion.

**Comment by openipka** [comment] 2021-07-29 13:54
> You don't want the gregtech-energy-api and gregtech-sources jar loaded in production.
> These are used for development.
> With these loaded and the main gregtech jar loaded you will have duplicate classes and assets.
> 
> I don't know if that is the cause of your problem, just a suggestion.

Well, I do removed those two mods, but the problem still exists.
And yes, I think removal of these two mods have no effects on the game itself.

**Comment by pablocnvs** [comment] 2021-07-29 13:57
The laser engraver casing will be solved in #507, though it might take a while to merge because it is a very extensive pr.

**Comment by DStrand1** [comment] 2021-11-29 22:28
Closed as of #582 and #507

**Closed by DStrand1** 2021-11-29 22:28 UTC
