### ISSUE TITLE
[Feature request] Multiblock solar array

### ISSUE THREAD

**Issue by alfuken** [GregTechCEu/gregicality#570] opened 2021-07-27 00:34 UTC
Can I haz featurerequest? Using lots of solar panels on wires can be quite lag-generating. Would be nice to have a multiblock machine, free-form-but-square-ish, which would just have a controller and a bunch of non-TE blocks attached.
LV version would be up to 16 photovoltaic blocks max (because of 16 amps max), MV - up to 64 PV blocks (64bl * 32V = 2048W = 128V * 16A, HV - up to 256 PV blocks (16x16, for example) (256bl * 32V = 8192W = 512V * 16A), and so on.

Alas, I am not that good (yet) in MC modding as to implement this myself, but it doesn't sound too complicated... or is it?

Thanks!

**Comment by alfuken** [comment] 2021-07-27 00:37
Or just add tiered versions of PV covers... Which would be simpler but a tad more boring...

**Comment by brachy84** [comment] 2021-07-27 16:09
we are not enviromental tech

**Comment by brachy84** [comment] 2021-07-27 16:15
We decided long ago to not implement solar panels or any form of passive generators. They are op and don't fit into greg tech

**Comment by trerri** [comment] 2021-07-27 16:39
If solar panels had a half-life of sorts where they would need to be replaced after breaking due to wear, and produced little power when the sky was "cloudy" (read random power fluctuations) and if skipping through the night made them wear as much as if you hadn't done that, then maybe it would be balanced and/or engaging. But there shouldn't be any better photovoltaic cell than the ULV one, just an array multiblock to make it less laggy. This sounds like a huge project though, and you guys have enough of those.

**Comment by alfuken** [comment] 2021-07-27 16:40
Well, you see, there are already solar panels in GTCE. It's not a question whether you're gonna implement them or not - they are there. The question is only about lag generation.
I can't tell my players on server "do not place too many solars or it'll lag" — they will do it anyway. The only **real** question here is lag mitigation.

**Comment by brachy84** [comment] 2021-07-27 16:42
by banning solars

**Comment by alfuken** [comment] 2021-07-27 16:42
Thanks, cpt. Obvious! 👍

**Comment by brachy84** [comment] 2021-07-27 16:53
Sorry, if I was rude. What I meant to say is, we will not add more solar panels to gregicality. If you want solar panels you can look into mods like enviromental tech (and use converters) or make your own mutiblock with multiblocktweaker.

**Comment by Syrcan** [comment] 2021-07-27 17:10
I would like to bring some insight.
(Passive) Solar Generators only currently exist as steam boiler, and as covers up to LV (32 eu/t). It is a cheap early game powergen, and a way to power select remote machines without worrying about wiring them.
Any passive generator meant to power a non-early game base does not exist, and will continue to not exist within GTCE/Gregicality.
&nbsp;
>
> I can't tell my players on server "do not place too many solars or it'll lag"
>
Well, sad truth is: you won't go far in the game with 32eu/t solars, even if you spam them. Also that's an expensive investment compared to using a more conventional approach. Each subsequent power tier is 4x the previous one, so every 2-3 tiers players are encouraged to switch over to a different power source. That's also what GregTech is about.

It's not out of question that more solar panels get to see their implementation in GTCE, however the idea will remain the same. They will be expensive and not suitable to give enough power relative to your current tier.

**Comment by huneau** [comment] 2021-08-18 09:54
related to #164

**Comment by DStrand1** [comment] 2021-11-29 22:22
Closing as a duplicate of #164

**Closed by DStrand1** 2021-11-29 22:22 UTC
